// Code generated by monad_gen, DO NOT EDIT.
package try

import (
	"github.com/csgura/fp"
	"github.com/csgura/fp/seq"
)

func PureSeqT[A any](a A) fp.Try[fp.Seq[A]] {
	return Pure(seq.Pure(a))
}

func MapSeqT[A any, B any](t fp.Try[fp.Seq[A]], f func(A) B) fp.Try[fp.Seq[B]] {
	return Map(t, func(ma fp.Seq[A]) fp.Seq[B] {
		return seq.FlatMap(ma, func(a A) fp.Seq[B] {
			return seq.Pure(f(a))
		})
	})
}

func SubFlatMapSeqT[A any, B any](t fp.Try[fp.Seq[A]], f func(A) fp.Seq[B]) fp.Try[fp.Seq[B]] {
	return Map(t, func(ma fp.Seq[A]) fp.Seq[B] {
		return seq.FlatMap(ma, func(a A) fp.Seq[B] {
			return f(a)
		})
	})
}
