// Code generated by monad_gen, DO NOT EDIT.
package try

import (
	"github.com/csgura/fp"
	"github.com/csgura/fp/option"
)

func PureOptionT[A any](a A) fp.Try[fp.Option[A]] {
	return Pure(option.Pure(a))
}

func MapOptionT[A any, B any](t fp.Try[fp.Option[A]], f func(A) B) fp.Try[fp.Option[B]] {
	return Map(t, func(ma fp.Option[A]) fp.Option[B] {
		return option.FlatMap(ma, func(a A) fp.Option[B] {
			return option.Pure(f(a))
		})
	})
}

func SubFlatMapOptionT[A any, B any](t fp.Try[fp.Option[A]], f func(A) fp.Option[B]) fp.Try[fp.Option[B]] {
	return Map(t, func(ma fp.Option[A]) fp.Option[B] {
		return option.FlatMap(ma, func(a A) fp.Option[B] {
			return f(a)
		})
	})
}
