// Code generated by gombok, DO NOT EDIT.
package namedptr

import (
	"github.com/csgura/fp"
	"github.com/csgura/fp/as"
	"time"
)

func ValidatorHello() Validator[Hello] {
	return ContraGeneric(
		"namedptr.Hello",
		"Struct",
		Struct2(NamedInt(as.NameTag(`v`, ``)), NamedSlice(as.NameTag(`s`, ``), Int)),
		func(v Hello) fp.Tuple2[int, []int] {
			return fp.Tuple2[int, []int]{
				I1: v.v,
				I2: v.s,
			}
		},
	)
}

func ValidatorContainer() Validator[Container] {
	return ContraGeneric(
		"namedptr.Container",
		"Struct",
		Struct1Container(NamedSlice(as.NameTag(`List`, ``), ValidatorValue())),
		func(v Container) fp.Tuple1[[]Value] {
			return fp.Tuple1[[]Value]{
				I1: v.List,
			}
		},
	)
}

func ValidatorValue() Validator[Value] {
	return ContraGeneric(
		"namedptr.Value",
		"Struct",
		Struct2(NamedInt(as.NameTag(`Present`, ``)), NamedPtr[time.Time](as.NameTag(`Value`, ``))),
		func(v Value) fp.Tuple2[int, *time.Time] {
			return fp.Tuple2[int, *time.Time]{
				I1: v.Present,
				I2: v.Value,
			}
		},
	)
}
