// Code generated by gombok, DO NOT EDIT.
package gendebug

import (
	"fmt"
	"github.com/csgura/fp"
	"github.com/csgura/fp/as"
	"github.com/csgura/fp/product"
	"github.com/csgura/fp/test/internal/show"
)

func ShowShowConstraintExplicit[T fmt.Stringer](showT fp.Show[T]) fp.Show[ShowConstraintExplicit[T]] {
	return show.Generic(
		as.Generic(
			"gendebug.ShowConstraintExplicit",
			"Struct",
			fp.Compose(
				func(v ShowConstraintExplicit[T]) fp.Tuple3[string, int, T] {
					return as.Tuple3(v.hello, v.world, v.message)
				},
				as.HList3,
			),

			fp.Compose(
				product.TupleFromHList3,
				func(t fp.Tuple3[string, int, T]) ShowConstraintExplicit[T] {
					return ShowConstraintExplicit[T]{
						hello:   t.I1,
						world:   t.I2,
						message: t.I3,
					}
				},
			),
		),
		show.StructHCons(
			show.String,
			show.StructHCons(
				show.Int[int](),
				show.StructHCons(
					showT,
					show.HNil,
				),
			),
		),
	)
}
