// Code generated by template_gen, DO NOT EDIT.
package xtr

// generated by xtr.go:28

func List[T interface{ List() V }, V any](t T) V {
	return t.List()
}

func Data[T interface{ Data() V }, V any](t T) V {
	return t.Data()
}

func DataList[T interface{ DataList() V }, V any](t T) V {
	return t.DataList()
}

func Response[T interface{ Response() V }, V any](t T) V {
	return t.Response()
}

func Get[T interface{ Get() V }, V any](t T) V {
	return t.Get()
}

func Left[T interface{ Left() V }, V any](t T) V {
	return t.Left()
}

func Key[T interface{ Key() V }, V any](t T) V {
	return t.Key()
}

func GetKey[T interface{ GetKey() V }, V any](t T) V {
	return t.GetKey()
}

func Value[T interface{ Value() V }, V any](t T) V {
	return t.Value()
}

func GetValue[T interface{ GetValue() V }, V any](t T) V {
	return t.GetValue()
}

func Meta[T interface{ Meta() V }, V any](t T) V {
	return t.Meta()
}

func ID[T interface{ ID() V }, V any](t T) V {
	return t.ID()
}

func Id[T interface{ Id() V }, V any](t T) V {
	return t.Id()
}

func Iterator[T interface{ Iterator() V }, V any](t T) V {
	return t.Iterator()
}

func Len[T interface{ Len() V }, V any](t T) V {
	return t.Len()
}

func Size[T interface{ Size() V }, V any](t T) V {
	return t.Size()
}

func Failed[T interface{ Failed() V }, V any](t T) V {
	return t.Failed()
}

func Context[T interface{ Context() V }, V any](t T) V {
	return t.Context()
}

func Unwrap[T interface{ Unwrap() V }, V any](t T) V {
	return t.Unwrap()
}

// generated by xtr.go:59

func IsDefined[T interface{ IsDefined() bool }](t T) bool {
	return t.IsDefined()
}

func IsEmpty[T interface{ IsEmpty() bool }](t T) bool {
	return t.IsEmpty()
}

func IsSuccess[T interface{ IsSuccess() bool }](t T) bool {
	return t.IsSuccess()
}

func IsFailure[T interface{ IsFailure() bool }](t T) bool {
	return t.IsFailure()
}

func IsLeft[T interface{ IsLeft() bool }](t T) bool {
	return t.IsLeft()
}

func IsRight[T interface{ IsRight() bool }](t T) bool {
	return t.IsRight()
}
