// Code generated by template_gen, DO NOT EDIT.
package xtr

// generated by xtr.go:28

func List[T interface{ List() V }, V any](t T) V {
	return t.List()
}

func GetList[T interface{ GetList() V }, V any](t T) V {
	return t.GetList()
}

func Data[T interface{ Data() V }, V any](t T) V {
	return t.Data()
}

func GetData[T interface{ GetData() V }, V any](t T) V {
	return t.GetData()
}

func DataList[T interface{ DataList() V }, V any](t T) V {
	return t.DataList()
}

func GetDataList[T interface{ GetDataList() V }, V any](t T) V {
	return t.GetDataList()
}

func Response[T interface{ Response() V }, V any](t T) V {
	return t.Response()
}

func GetResponse[T interface{ GetResponse() V }, V any](t T) V {
	return t.GetResponse()
}

func Left[T interface{ Left() V }, V any](t T) V {
	return t.Left()
}

func GetLeft[T interface{ GetLeft() V }, V any](t T) V {
	return t.GetLeft()
}

func Key[T interface{ Key() V }, V any](t T) V {
	return t.Key()
}

func GetKey[T interface{ GetKey() V }, V any](t T) V {
	return t.GetKey()
}

func Name[T interface{ Name() V }, V any](t T) V {
	return t.Name()
}

func GetName[T interface{ GetName() V }, V any](t T) V {
	return t.GetName()
}

func Value[T interface{ Value() V }, V any](t T) V {
	return t.Value()
}

func GetValue[T interface{ GetValue() V }, V any](t T) V {
	return t.GetValue()
}

func Meta[T interface{ Meta() V }, V any](t T) V {
	return t.Meta()
}

func GetMeta[T interface{ GetMeta() V }, V any](t T) V {
	return t.GetMeta()
}

func ID[T interface{ ID() V }, V any](t T) V {
	return t.ID()
}

func GetID[T interface{ GetID() V }, V any](t T) V {
	return t.GetID()
}

func Id[T interface{ Id() V }, V any](t T) V {
	return t.Id()
}

func GetId[T interface{ GetId() V }, V any](t T) V {
	return t.GetId()
}

func Len[T interface{ Len() V }, V any](t T) V {
	return t.Len()
}

func GetLen[T interface{ GetLen() V }, V any](t T) V {
	return t.GetLen()
}

func Size[T interface{ Size() V }, V any](t T) V {
	return t.Size()
}

func GetSize[T interface{ GetSize() V }, V any](t T) V {
	return t.GetSize()
}

func Failed[T interface{ Failed() V }, V any](t T) V {
	return t.Failed()
}

func GetFailed[T interface{ GetFailed() V }, V any](t T) V {
	return t.GetFailed()
}

func Context[T interface{ Context() V }, V any](t T) V {
	return t.Context()
}

func GetContext[T interface{ GetContext() V }, V any](t T) V {
	return t.GetContext()
}

// generated by xtr.go:59

func Get[T interface{ Get() V }, V any](t T) V {
	return t.Get()
}

func Unwrap[T interface{ Unwrap() V }, V any](t T) V {
	return t.Unwrap()
}

func Iterator[T interface{ Iterator() V }, V any](t T) V {
	return t.Iterator()
}

// generated by xtr.go:74

func IsDefined[T interface{ IsDefined() bool }](t T) bool {
	return t.IsDefined()
}

func IsEmpty[T interface{ IsEmpty() bool }](t T) bool {
	return t.IsEmpty()
}

func IsSuccess[T interface{ IsSuccess() bool }](t T) bool {
	return t.IsSuccess()
}

func IsFailure[T interface{ IsFailure() bool }](t T) bool {
	return t.IsFailure()
}

func IsLeft[T interface{ IsLeft() bool }](t T) bool {
	return t.IsLeft()
}

func IsRight[T interface{ IsRight() bool }](t T) bool {
	return t.IsRight()
}
