// Code generated by gombok, DO NOT EDIT.
package state

import (
	"github.com/csgura/fp"
	"github.com/csgura/fp/iterator"
)

func Traverse[S any, A any, R any](ia fp.Iterator[A], fn func(A) fp.State[S, R]) fp.State[S, fp.Iterator[R]] {
	return Map(FoldM(ia, fp.Seq[R]{}, func(acc fp.Seq[R], a A) fp.State[S, fp.Seq[R]] {
		return Map(fn(a), acc.Add)
	}), iterator.FromSeq)
}

func TraverseSeq[S any, A any, R any](sa fp.Seq[A], fa func(A) fp.State[S, R]) fp.State[S, fp.Seq[R]] {
	return FoldM(fp.IteratorOfSeq(sa), fp.Seq[R]{}, func(acc fp.Seq[R], a A) fp.State[S, fp.Seq[R]] {
		return Map(fa(a), acc.Add)
	})
}

func TraverseSlice[S any, A any, R any](sa []A, fa func(A) fp.State[S, R]) fp.State[S, []R] {
	return Map(TraverseSeq(sa, fa), fp.Seq[R].Widen)
}

func TraverseFunc[S any, A any, R any](far func(A) fp.State[S, R]) func(fp.Iterator[A]) fp.State[S, fp.Iterator[R]] {
	return func(iterA fp.Iterator[A]) fp.State[S, fp.Iterator[R]] {
		return Traverse(iterA, far)
	}
}

func TraverseSeqFunc[S any, A any, R any](far func(A) fp.State[S, R]) func(fp.Seq[A]) fp.State[S, fp.Seq[R]] {
	return func(seqA fp.Seq[A]) fp.State[S, fp.Seq[R]] {
		return TraverseSeq(seqA, far)
	}
}

func TraverseSliceFunc[S any, A any, R any](far func(A) fp.State[S, R]) func([]A) fp.State[S, []R] {
	return func(seqA []A) fp.State[S, []R] {
		return TraverseSlice(seqA, far)
	}
}

func FlatMapTraverseSeq[S any, A any, B any](ta fp.State[S, fp.Seq[A]], f func(v A) fp.State[S, B]) fp.State[S, fp.Seq[B]] {
	return FlatMap(ta, TraverseSeqFunc(f))
}

func FlatMapTraverseSlice[S any, A any, B any](ta fp.State[S, []A], f func(v A) fp.State[S, B]) fp.State[S, []B] {
	return FlatMap(ta, TraverseSliceFunc(f))
}

func Sequence[S any, A any](tsa []fp.State[S, A]) fp.State[S, []A] {
	ret := FoldM(iterator.FromSeq(tsa), fp.Seq[A]{}, func(t1 fp.Seq[A], t2 fp.State[S, A]) fp.State[S, fp.Seq[A]] {
		return Map(t2, t1.Add)
	})

	return Map(ret, fp.Seq[A].Widen)
}

func SequenceIterator[S any, A any](ita fp.Iterator[fp.State[S, A]]) fp.State[S, fp.Iterator[A]] {
	ret := FoldM(ita, fp.Seq[A]{}, func(t1 fp.Seq[A], t2 fp.State[S, A]) fp.State[S, fp.Seq[A]] {
		return Map(t2, t1.Add)
	})
	return Map(ret, iterator.FromSeq)

}
