// Code generated by gombok, DO NOT EDIT.
package testjson

import (
	"github.com/csgura/fp"
	"github.com/csgura/fp/as"
	"github.com/csgura/fp/lazy"
	"github.com/csgura/fp/product"
	"github.com/csgura/fp/test/internal/js"
)

func EncoderRoot() js.Encoder[Root] {
	return js.EncoderContraMap(
		js.EncoderHConsLabelled(
			js.EncoderNamed[NamedAOfRoot, int](js.EncoderNumber[int]()),
			js.EncoderHConsLabelled(
				js.EncoderNamed[NamedBOfRoot, string](js.EncoderString),
				js.EncoderHConsLabelled(
					js.EncoderNamed[NamedCOfRoot, float64](js.EncoderNumber[float64]()),
					js.EncoderHConsLabelled(
						js.EncoderNamed[NamedDOfRoot, bool](js.EncoderBool),
						js.EncoderHConsLabelled(
							js.EncoderNamed[NamedEOfRoot, *int](js.EncoderPtr(lazy.Call(func() js.Encoder[int] {
								return js.EncoderNumber[int]()
							}))),
							js.EncoderHConsLabelled(
								js.EncoderNamed[NamedFOfRoot, []int](js.EncoderSlice(js.EncoderNumber[int]())),
								js.EncoderHConsLabelled(
									js.EncoderNamed[NamedGOfRoot, map[string]int](js.EncoderGoMap(js.EncoderNumber[int]())),
									js.EncoderHConsLabelled(
										js.EncoderNamed[NamedHOfRoot, Child](EncoderChild()),
										js.EncoderHNil,
									),
								),
							),
						),
					),
				),
			),
		),
		fp.Compose(
			Root.AsLabelled,
			as.HList8Labelled,
		),
	)
}

func DecoderRoot() js.Decoder[Root] {
	return js.DecoderMap(
		js.DecoderHConsLabelled(
			js.DecoderNamed[NamedAOfRoot, int](js.DecoderNumber[int]()),
			js.DecoderHConsLabelled(
				js.DecoderNamed[NamedBOfRoot, string](js.DecoderString),
				js.DecoderHConsLabelled(
					js.DecoderNamed[NamedCOfRoot, float64](js.DecoderNumber[float64]()),
					js.DecoderHConsLabelled(
						js.DecoderNamed[NamedDOfRoot, bool](js.DecoderBool),
						js.DecoderHConsLabelled(
							js.DecoderNamed[NamedEOfRoot, *int](js.DecoderPtr(lazy.Call(func() js.Decoder[int] {
								return js.DecoderNumber[int]()
							}))),
							js.DecoderHConsLabelled(
								js.DecoderNamed[NamedFOfRoot, []int](js.DecoderSlice(js.DecoderNumber[int]())),
								js.DecoderHConsLabelled(
									js.DecoderNamed[NamedGOfRoot, map[string]int](js.DecoderGoMap(js.DecoderNumber[int]())),
									js.DecoderHConsLabelled(
										js.DecoderNamed[NamedHOfRoot, Child](DecoderChild()),
										js.DecoderHNil,
									),
								),
							),
						),
					),
				),
			),
		),

		fp.Compose(
			product.LabelledFromHList8,
			fp.Compose(
				as.Curried2(RootBuilder.FromLabelled)(RootBuilder{}),
				RootBuilder.Build,
			),
		),
	)
}

func EncoderChild() js.Encoder[Child] {
	return js.EncoderContraMap(
		js.EncoderLabelled2(js.EncoderNamed[NamedAOfChild, map[string]any](js.EncoderGoMapAny), js.EncoderNamed[NamedBOfChild, any](js.EncoderGiven[any]())),
		Child.AsLabelled,
	)
}

func DecoderChild() js.Decoder[Child] {
	return js.DecoderMap(
		js.DecoderLabelled2(js.DecoderNamed[NamedAOfChild, map[string]any](js.DecoderGoMapAny), js.DecoderNamed[NamedBOfChild, any](js.DecoderGiven[any]())),
		fp.Compose(
			as.Curried2(ChildBuilder.FromLabelled)(ChildBuilder{}),
			ChildBuilder.Build,
		),
	)
}

func EncoderNode() js.Encoder[Node] {
	return js.EncoderContraMap(
		js.EncoderHConsLabelled(
			js.EncoderNamed[NamedNameOfNode, string](js.EncoderString),
			js.EncoderHConsLabelled(
				js.EncoderNamed[NamedLeftOfNode, *Node](js.EncoderPtr(lazy.Call(func() js.Encoder[Node] {
					return EncoderNode()
				}))),
				js.EncoderHConsLabelled(
					js.EncoderNamed[NamedRightOfNode, *Node](js.EncoderPtr(lazy.Call(func() js.Encoder[Node] {
						return EncoderNode()
					}))),
					js.EncoderHNil,
				),
			),
		),
		fp.Compose(
			Node.AsLabelled,
			as.HList3Labelled,
		),
	)
}

func EncoderTree() js.Encoder[Tree] {
	return js.EncoderContraMap(
		js.EncoderLabelled1(js.EncoderNamed[NamedRootOfTree, *Node](js.EncoderPtr(lazy.Call(func() js.Encoder[Node] {
			return EncoderNode()
		})))),
		Tree.AsLabelled,
	)
}

func EncoderEntry[V any](encoderV js.Encoder[V]) js.Encoder[Entry[V]] {
	return js.EncoderContraMap(
		js.EncoderLabelled2(js.EncoderNamed[NamedNameOfEntry, string](js.EncoderString), js.EncoderNamed[NamedValueOfEntry[V], V](encoderV)),
		Entry[V].AsLabelled,
	)
}

func EncoderNotUsedParam[K any, V any](encoderV js.Encoder[V]) js.Encoder[NotUsedParam[K, V]] {
	return js.EncoderContraMap(
		js.EncoderLabelled2(js.EncoderNamed[NamedParamOfNotUsedParam, string](js.EncoderString), js.EncoderNamed[NamedValueOfNotUsedParam[V], V](encoderV)),
		NotUsedParam[K, V].AsLabelled,
	)
}

func EncoderMovie() js.Encoder[Movie] {
	return js.EncoderContraMap(
		js.EncoderHConsLabelled(
			js.EncoderNamed[NamedNameOfMovie, string](js.EncoderString),
			js.EncoderHConsLabelled(
				js.EncoderNamed[NamedCastingOfMovie, Entry[string]](EncoderEntry(js.EncoderString)),
				js.EncoderHConsLabelled(
					js.EncoderNamed[NamedNotUsedOfMovie, NotUsedParam[int, string]](EncoderNotUsedParam[int, string](js.EncoderString)),
					js.EncoderHNil,
				),
			),
		),
		fp.Compose(
			Movie.AsLabelled,
			as.HList3Labelled,
		),
	)
}

func EncoderNoPrivate() js.Encoder[NoPrivate] {
	return js.EncoderContraMap(
		js.EncoderLabelled1(js.EncoderNamed[PubNamedRootOfNoPrivate, string](js.EncoderString)),
		NoPrivate.AsLabelled,
	)
}

func DecoderNoPrivate() js.Decoder[NoPrivate] {
	return js.DecoderMap(
		js.DecoderHConsLabelled(
			js.DecoderNamed[PubNamedRootOfNoPrivate, string](js.DecoderString),
			js.DecoderHNil,
		),

		fp.Compose(
			product.LabelledFromHList1,
			fp.Compose(
				as.Curried2(NoPrivateBuilder.FromLabelled)(NoPrivateBuilder{}),
				NoPrivateBuilder.Build,
			),
		),
	)
}
