// Code generated by template_gen, DO NOT EDIT.
package tctx

import (
	"context"
	"github.com/csgura/fp"
	"github.com/csgura/fp/as"
	"github.com/csgura/fp/tstate"
)

func Fit3[A1, A2, R any](f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, R]]]) fp.Func1[context.Context, fp.Func1[A2, fp.Func1[A1, R]]] {
	return as.Curried3(func(ctx context.Context, a2 A2, a1 A1) R {
		return f(ctx)(a1)(a2)

	})
}

func Fit4[A1, A2, A3, R any](f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, R]]]]) fp.Func1[context.Context, fp.Func1[A3, fp.Func1[A1, fp.Func1[A2, R]]]] {
	return as.Curried4(func(ctx context.Context, a3 A3, a1 A1, a2 A2) R {
		return f(ctx)(a1)(a2)(a3)

	})
}

func Fit5[A1, A2, A3, A4, R any](f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, R]]]]]) fp.Func1[context.Context, fp.Func1[A4, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, R]]]]] {
	return as.Curried5(func(ctx context.Context, a4 A4, a1 A1, a2 A2, a3 A3) R {
		return f(ctx)(a1)(a2)(a3)(a4)

	})
}

func Fit6[A1, A2, A3, A4, A5, R any](f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, fp.Func1[A5, R]]]]]]) fp.Func1[context.Context, fp.Func1[A5, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, R]]]]]] {
	return as.Curried6(func(ctx context.Context, a5 A5, a1 A1, a2 A2, a3 A3, a4 A4) R {
		return f(ctx)(a1)(a2)(a3)(a4)(a5)

	})
}

func Fit7[A1, A2, A3, A4, A5, A6, R any](f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, fp.Func1[A5, fp.Func1[A6, R]]]]]]]) fp.Func1[context.Context, fp.Func1[A6, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, fp.Func1[A5, R]]]]]]] {
	return as.Curried7(func(ctx context.Context, a6 A6, a1 A1, a2 A2, a3 A3, a4 A4, a5 A5) R {
		return f(ctx)(a1)(a2)(a3)(a4)(a5)(a6)

	})
}

func Fit8[A1, A2, A3, A4, A5, A6, A7, R any](f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, fp.Func1[A5, fp.Func1[A6, fp.Func1[A7, R]]]]]]]]) fp.Func1[context.Context, fp.Func1[A7, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, fp.Func1[A5, fp.Func1[A6, R]]]]]]]] {
	return as.Curried8(func(ctx context.Context, a7 A7, a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6) R {
		return f(ctx)(a1)(a2)(a3)(a4)(a5)(a6)(a7)

	})
}

func Fit9[A1, A2, A3, A4, A5, A6, A7, A8, R any](f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, fp.Func1[A5, fp.Func1[A6, fp.Func1[A7, fp.Func1[A8, R]]]]]]]]]) fp.Func1[context.Context, fp.Func1[A8, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, fp.Func1[A5, fp.Func1[A6, fp.Func1[A7, R]]]]]]]]] {
	return as.Curried9(func(ctx context.Context, a8 A8, a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7) R {
		return f(ctx)(a1)(a2)(a3)(a4)(a5)(a6)(a7)(a8)

	})
}

func MapPureArg1[A1, A2, R any](s State[A1], f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, R]]], a2 A2) State[R] {
	return Narrow(tstate.MapWithState(Widen(s), func(s context.Context, a1 A1) R {
		return f(s)(a1)(a2)
	}))
}

func MapPureArg2[A1, A2, A3, R any](s State[A1], f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, R]]]], a2 A2, a3 A3) State[R] {
	return Narrow(tstate.MapWithState(Widen(s), func(s context.Context, a1 A1) R {
		return f(s)(a1)(a2)(a3)
	}))
}

func MapPureArg3[A1, A2, A3, A4, R any](s State[A1], f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, R]]]]], a2 A2, a3 A3, a4 A4) State[R] {
	return Narrow(tstate.MapWithState(Widen(s), func(s context.Context, a1 A1) R {
		return f(s)(a1)(a2)(a3)(a4)
	}))
}

func MapPureArg4[A1, A2, A3, A4, A5, R any](s State[A1], f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, fp.Func1[A5, R]]]]]], a2 A2, a3 A3, a4 A4, a5 A5) State[R] {
	return Narrow(tstate.MapWithState(Widen(s), func(s context.Context, a1 A1) R {
		return f(s)(a1)(a2)(a3)(a4)(a5)
	}))
}

func MapPureArg5[A1, A2, A3, A4, A5, A6, R any](s State[A1], f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, fp.Func1[A5, fp.Func1[A6, R]]]]]]], a2 A2, a3 A3, a4 A4, a5 A5, a6 A6) State[R] {
	return Narrow(tstate.MapWithState(Widen(s), func(s context.Context, a1 A1) R {
		return f(s)(a1)(a2)(a3)(a4)(a5)(a6)
	}))
}

func MapPureArg6[A1, A2, A3, A4, A5, A6, A7, R any](s State[A1], f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, fp.Func1[A5, fp.Func1[A6, fp.Func1[A7, R]]]]]]]], a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7) State[R] {
	return Narrow(tstate.MapWithState(Widen(s), func(s context.Context, a1 A1) R {
		return f(s)(a1)(a2)(a3)(a4)(a5)(a6)(a7)
	}))
}

func MapPureArg7[A1, A2, A3, A4, A5, A6, A7, A8, R any](s State[A1], f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, fp.Func1[A5, fp.Func1[A6, fp.Func1[A7, fp.Func1[A8, R]]]]]]]]], a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8) State[R] {
	return Narrow(tstate.MapWithState(Widen(s), func(s context.Context, a1 A1) R {
		return f(s)(a1)(a2)(a3)(a4)(a5)(a6)(a7)(a8)
	}))
}

func MapPureArg8[A1, A2, A3, A4, A5, A6, A7, A8, A9, R any](s State[A1], f fp.Func1[context.Context, fp.Func1[A1, fp.Func1[A2, fp.Func1[A3, fp.Func1[A4, fp.Func1[A5, fp.Func1[A6, fp.Func1[A7, fp.Func1[A8, fp.Func1[A9, R]]]]]]]]]], a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8, a9 A9) State[R] {
	return Narrow(tstate.MapWithState(Widen(s), func(s context.Context, a1 A1) R {
		return f(s)(a1)(a2)(a3)(a4)(a5)(a6)(a7)(a8)(a9)
	}))
}
