// Code generated by monad_gen, DO NOT EDIT.
package genericgen

import (
	"github.com/csgura/fp"
)

func (m Identity[A]) Map[R any](f func(A) R) Identity[R] {
	return m.FlatMap(func(a A) Identity[R] {
		return Pure[R](f(a))
	})
}

// haskell 의 <$
// map . const 와 같은 함수
func (m Identity[A]) Replace[R any](b R) Identity[R] {
	return m.Map(fp.Const[A](b))
}

// Replace fp.Unit{}
func (m Identity[A]) Void[_ fp.Phantom[A]]() Identity[fp.Unit] {
	return m.Replace(fp.Unit{})
}

func (m Identity[A]) Map2[B, R any](second Identity[B], fab func(A, B) R) Identity[R] {
	return m.FlatMap(func(a A) Identity[R] {
		return second.Map(func(b B) R {
			return fab(a, b)
		})
	})
}

func (m Identity[A]) FlatMap2[B, R any](second Identity[B], fab func(A, B) Identity[R]) Identity[R] {
	return m.FlatMap(func(a A) Identity[R] {
		return second.FlatMap(func(b B) Identity[R] {
			return fab(a, b)
		})
	})
}

// FlatMap 과는 아규먼트 순서가 다른 함수로
// Go 나 Java 에서는 메소드 레퍼런스를 이용하여,  객체내의 메소드를 리턴 타입만 lift 된 형태로 리턴하게 할 수 있음.
// Method 라는 이름보다  Ap 와 비슷한 이름이 좋을 거 같은데
// Ap와 비슷한 이름으로 하기에는 Ap 와 타입이 너무 다름.
func (m Identity[A]) Method1[B, R any](fab func(a A, b B) R) func(B) Identity[R] {
	return func(b B) Identity[R] {
		return m.Map(func(a A) R {
			return fab(a, b)
		})
	}
}

func (m Identity[A]) FlatMethod1[B, R any](ta Identity[A], fab func(a A, b B) Identity[R]) func(B) Identity[R] {
	return func(b B) Identity[R] {
		return m.FlatMap(func(a A) Identity[R] {
			return fab(a, b)
		})
	}
}

func (m Identity[A]) Method2[B, C, R any](fabc func(a A, b B, c C) R) func(B, C) Identity[R] {
	return func(b B, c C) Identity[R] {
		return m.Map(func(a A) R {
			return fabc(a, b, c)
		})
	}
}

func (m Identity[A]) FlatMethod2[B, C, R any](fabc func(a A, b B, c C) Identity[R]) func(B, C) Identity[R] {
	return func(b B, c C) Identity[R] {
		return m.FlatMap(func(a A) Identity[R] {
			return fabc(a, b, c)
		})
	}
}

// fp.With 의 monad 버젼
// fp.With 가 Flip 과 사실상 같은 것처럼
// FlapMap 의 Flip 버젼과 동일
// var b fp.Try[B]
// a := try.Sucesss(A{})
// a.FlatMap(b.With(A.WithB))
// 형태로 코딩 가능
func (m Identity[A]) With[S any](withf func(S, A) S) func(S) Identity[S] {
	return m.Method1(func(a A, s S) S {
		return withf(s, a)
	})
}

func (ins1 Identity[A1]) Map3[A2, A3, R any](ins2 Identity[A2], ins3 Identity[A3], f func(a1 A1, a2 A2, a3 A3) R) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.Map2(ins3, func(a2 A2, a3 A3) R {
			return f(a1, a2, a3)
		})
	})
}

func (ins1 Identity[A1]) Map4[A2, A3, A4, R any](ins2 Identity[A2], ins3 Identity[A3], ins4 Identity[A4], f func(a1 A1, a2 A2, a3 A3, a4 A4) R) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.Map3(ins3, ins4, func(a2 A2, a3 A3, a4 A4) R {
			return f(a1, a2, a3, a4)
		})
	})
}

func (ins1 Identity[A1]) Map5[A2, A3, A4, A5, R any](ins2 Identity[A2], ins3 Identity[A3], ins4 Identity[A4], ins5 Identity[A5], f func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5) R) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.Map4(ins3, ins4, ins5, func(a2 A2, a3 A3, a4 A4, a5 A5) R {
			return f(a1, a2, a3, a4, a5)
		})
	})
}

func (ins1 Identity[A1]) Map6[A2, A3, A4, A5, A6, R any](ins2 Identity[A2], ins3 Identity[A3], ins4 Identity[A4], ins5 Identity[A5], ins6 Identity[A6], f func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6) R) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.Map5(ins3, ins4, ins5, ins6, func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6) R {
			return f(a1, a2, a3, a4, a5, a6)
		})
	})
}

func (ins1 Identity[A1]) Map7[A2, A3, A4, A5, A6, A7, R any](ins2 Identity[A2], ins3 Identity[A3], ins4 Identity[A4], ins5 Identity[A5], ins6 Identity[A6], ins7 Identity[A7], f func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7) R) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.Map6(ins3, ins4, ins5, ins6, ins7, func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7) R {
			return f(a1, a2, a3, a4, a5, a6, a7)
		})
	})
}

func (ins1 Identity[A1]) Map8[A2, A3, A4, A5, A6, A7, A8, R any](ins2 Identity[A2], ins3 Identity[A3], ins4 Identity[A4], ins5 Identity[A5], ins6 Identity[A6], ins7 Identity[A7], ins8 Identity[A8], f func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8) R) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.Map7(ins3, ins4, ins5, ins6, ins7, ins8, func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8) R {
			return f(a1, a2, a3, a4, a5, a6, a7, a8)
		})
	})
}

func (ins1 Identity[A1]) Map9[A2, A3, A4, A5, A6, A7, A8, A9, R any](ins2 Identity[A2], ins3 Identity[A3], ins4 Identity[A4], ins5 Identity[A5], ins6 Identity[A6], ins7 Identity[A7], ins8 Identity[A8], ins9 Identity[A9], f func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8, a9 A9) R) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.Map8(ins3, ins4, ins5, ins6, ins7, ins8, ins9, func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8, a9 A9) R {
			return f(a1, a2, a3, a4, a5, a6, a7, a8, a9)
		})
	})
}

func (ins1 Identity[A1]) FlatMap3[A2, A3, R any](ins2 Identity[A2], ins3 Identity[A3], f func(a1 A1, a2 A2, a3 A3) Identity[R]) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.FlatMap2(ins3, func(a2 A2, a3 A3) Identity[R] {
			return f(a1, a2, a3)
		})
	})
}

func (ins1 Identity[A1]) FlatMap4[A2, A3, A4, R any](ins2 Identity[A2], ins3 Identity[A3], ins4 Identity[A4], f func(a1 A1, a2 A2, a3 A3, a4 A4) Identity[R]) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.FlatMap3(ins3, ins4, func(a2 A2, a3 A3, a4 A4) Identity[R] {
			return f(a1, a2, a3, a4)
		})
	})
}

func (ins1 Identity[A1]) FlatMap5[A2, A3, A4, A5, R any](ins2 Identity[A2], ins3 Identity[A3], ins4 Identity[A4], ins5 Identity[A5], f func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5) Identity[R]) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.FlatMap4(ins3, ins4, ins5, func(a2 A2, a3 A3, a4 A4, a5 A5) Identity[R] {
			return f(a1, a2, a3, a4, a5)
		})
	})
}

func (ins1 Identity[A1]) FlatMap6[A2, A3, A4, A5, A6, R any](ins2 Identity[A2], ins3 Identity[A3], ins4 Identity[A4], ins5 Identity[A5], ins6 Identity[A6], f func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6) Identity[R]) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.FlatMap5(ins3, ins4, ins5, ins6, func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6) Identity[R] {
			return f(a1, a2, a3, a4, a5, a6)
		})
	})
}

func (ins1 Identity[A1]) FlatMap7[A2, A3, A4, A5, A6, A7, R any](ins2 Identity[A2], ins3 Identity[A3], ins4 Identity[A4], ins5 Identity[A5], ins6 Identity[A6], ins7 Identity[A7], f func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7) Identity[R]) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.FlatMap6(ins3, ins4, ins5, ins6, ins7, func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7) Identity[R] {
			return f(a1, a2, a3, a4, a5, a6, a7)
		})
	})
}

func (ins1 Identity[A1]) FlatMap8[A2, A3, A4, A5, A6, A7, A8, R any](ins2 Identity[A2], ins3 Identity[A3], ins4 Identity[A4], ins5 Identity[A5], ins6 Identity[A6], ins7 Identity[A7], ins8 Identity[A8], f func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8) Identity[R]) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.FlatMap7(ins3, ins4, ins5, ins6, ins7, ins8, func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8) Identity[R] {
			return f(a1, a2, a3, a4, a5, a6, a7, a8)
		})
	})
}

func (ins1 Identity[A1]) FlatMap9[A2, A3, A4, A5, A6, A7, A8, A9, R any](ins2 Identity[A2], ins3 Identity[A3], ins4 Identity[A4], ins5 Identity[A5], ins6 Identity[A6], ins7 Identity[A7], ins8 Identity[A8], ins9 Identity[A9], f func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8, a9 A9) Identity[R]) Identity[R] {
	return ins1.FlatMap(func(a1 A1) Identity[R] {
		return ins2.FlatMap8(ins3, ins4, ins5, ins6, ins7, ins8, ins9, func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8, a9 A9) Identity[R] {
			return f(a1, a2, a3, a4, a5, a6, a7, a8, a9)
		})
	})
}

func (m Identity[A1]) Method3[A2, A3, R any](fa1 func(a1 A1, a2 A2, a3 A3) R) func(A2, A3) Identity[R] {
	return func(a2 A2, a3 A3) Identity[R] {
		return m.Map(func(a1 A1) R {
			return fa1(a1, a2, a3)
		})
	}
}

func (m Identity[A1]) Method4[A2, A3, A4, R any](fa1 func(a1 A1, a2 A2, a3 A3, a4 A4) R) func(A2, A3, A4) Identity[R] {
	return func(a2 A2, a3 A3, a4 A4) Identity[R] {
		return m.Map(func(a1 A1) R {
			return fa1(a1, a2, a3, a4)
		})
	}
}

func (m Identity[A1]) Method5[A2, A3, A4, A5, R any](fa1 func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5) R) func(A2, A3, A4, A5) Identity[R] {
	return func(a2 A2, a3 A3, a4 A4, a5 A5) Identity[R] {
		return m.Map(func(a1 A1) R {
			return fa1(a1, a2, a3, a4, a5)
		})
	}
}

func (m Identity[A1]) Method6[A2, A3, A4, A5, A6, R any](fa1 func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6) R) func(A2, A3, A4, A5, A6) Identity[R] {
	return func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6) Identity[R] {
		return m.Map(func(a1 A1) R {
			return fa1(a1, a2, a3, a4, a5, a6)
		})
	}
}

func (m Identity[A1]) Method7[A2, A3, A4, A5, A6, A7, R any](fa1 func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7) R) func(A2, A3, A4, A5, A6, A7) Identity[R] {
	return func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7) Identity[R] {
		return m.Map(func(a1 A1) R {
			return fa1(a1, a2, a3, a4, a5, a6, a7)
		})
	}
}

func (m Identity[A1]) Method8[A2, A3, A4, A5, A6, A7, A8, R any](fa1 func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8) R) func(A2, A3, A4, A5, A6, A7, A8) Identity[R] {
	return func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8) Identity[R] {
		return m.Map(func(a1 A1) R {
			return fa1(a1, a2, a3, a4, a5, a6, a7, a8)
		})
	}
}

func (m Identity[A1]) Method9[A2, A3, A4, A5, A6, A7, A8, A9, R any](fa1 func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8, a9 A9) R) func(A2, A3, A4, A5, A6, A7, A8, A9) Identity[R] {
	return func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8, a9 A9) Identity[R] {
		return m.Map(func(a1 A1) R {
			return fa1(a1, a2, a3, a4, a5, a6, a7, a8, a9)
		})
	}
}

func (m Identity[A1]) FlatMethod3[A2, A3, R any](fa1 func(a1 A1, a2 A2, a3 A3) Identity[R]) func(A2, A3) Identity[R] {
	return func(a2 A2, a3 A3) Identity[R] {
		return m.FlatMap(func(a1 A1) Identity[R] {
			return fa1(a1, a2, a3)
		})
	}
}

func (m Identity[A1]) FlatMethod4[A2, A3, A4, R any](fa1 func(a1 A1, a2 A2, a3 A3, a4 A4) Identity[R]) func(A2, A3, A4) Identity[R] {
	return func(a2 A2, a3 A3, a4 A4) Identity[R] {
		return m.FlatMap(func(a1 A1) Identity[R] {
			return fa1(a1, a2, a3, a4)
		})
	}
}

func (m Identity[A1]) FlatMethod5[A2, A3, A4, A5, R any](fa1 func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5) Identity[R]) func(A2, A3, A4, A5) Identity[R] {
	return func(a2 A2, a3 A3, a4 A4, a5 A5) Identity[R] {
		return m.FlatMap(func(a1 A1) Identity[R] {
			return fa1(a1, a2, a3, a4, a5)
		})
	}
}

func (m Identity[A1]) FlatMethod6[A2, A3, A4, A5, A6, R any](fa1 func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6) Identity[R]) func(A2, A3, A4, A5, A6) Identity[R] {
	return func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6) Identity[R] {
		return m.FlatMap(func(a1 A1) Identity[R] {
			return fa1(a1, a2, a3, a4, a5, a6)
		})
	}
}

func (m Identity[A1]) FlatMethod7[A2, A3, A4, A5, A6, A7, R any](fa1 func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7) Identity[R]) func(A2, A3, A4, A5, A6, A7) Identity[R] {
	return func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7) Identity[R] {
		return m.FlatMap(func(a1 A1) Identity[R] {
			return fa1(a1, a2, a3, a4, a5, a6, a7)
		})
	}
}

func (m Identity[A1]) FlatMethod8[A2, A3, A4, A5, A6, A7, A8, R any](fa1 func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8) Identity[R]) func(A2, A3, A4, A5, A6, A7, A8) Identity[R] {
	return func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8) Identity[R] {
		return m.FlatMap(func(a1 A1) Identity[R] {
			return fa1(a1, a2, a3, a4, a5, a6, a7, a8)
		})
	}
}

func (m Identity[A1]) FlatMethod9[A2, A3, A4, A5, A6, A7, A8, A9, R any](fa1 func(a1 A1, a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8, a9 A9) Identity[R]) func(A2, A3, A4, A5, A6, A7, A8, A9) Identity[R] {
	return func(a2 A2, a3 A3, a4 A4, a5 A5, a6 A6, a7 A7, a8 A8, a9 A9) Identity[R] {
		return m.FlatMap(func(a1 A1) Identity[R] {
			return fa1(a1, a2, a3, a4, a5, a6, a7, a8, a9)
		})
	}
}
